### ISSUE TITLE
Logo for TeXworks

### ISSUE THREAD

**Issue by koppor** [cpierquet/vectorlogos#2]
TeXworks offers png and ico only. Would it possible to have a SVG version of it?

https://github.com/TeXworks/texworks/tree/main/res/images

---

I got the hint to vectorlogos from https://chat.stackexchange.com/transcript/message/65288288#65288288

**Comment by cpierquet** [comment]
TeXworks dont's offer svg... So I need to look at png for a conversion (if the license is compatible ^^)
Céd-

**Comment by cpierquet** [comment]
A try with the png version of the logo (scale 1 in the cap), converted to pdf (but not vectorial...)
![image](https://github.com/cpierquet/vectorlogos/assets/45103962/f66279a0-396b-41a6-bdb9-7bcdc9d8439f)

**Comment by koppor** [comment]
I think, it's too large.

Meanwhile, a team member created an own version: https://github.com/JabRef/jabref/pull/10998

Thus, closing this issue (to reduce load on your side)

**Comment by cpierquet** [comment]
It's the original size, but the package can insert 'inline' :-)
![image](https://github.com/cpierquet/vectorlogos/assets/45103962/f5e53d93-d5c0-43ff-9336-c9a09c22eb6a)
